//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string OrderDates { get; set; }
        public Nullable<int> status_bay { get; set; }
        public string OrderName { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual OrderDetails OrderDetails { get; set; }
        public virtual Products Products { get; set; }
    }
}
