//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int ProductID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> Price { get; set; }
        public string Details { get; set; }
        public Nullable<int> OrderID { get; set; }
    
        public virtual Categorys Categorys { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
